name: CORS Proxy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Ejecuta diariamente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run proxy server
        run: |
          npx http-server -p 8080 &
          sleep 5
          curl -X GET "http://localhost:8080/fetch-data"
